/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_paypal_rtdp_collections_util_JniThreadUtil */

#ifndef _Included_com_paypal_rtdp_collections_util_JniThreadUtil
#define _Included_com_paypal_rtdp_collections_util_JniThreadUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_paypal_rtdp_collections_util_JniThreadUtil
 * Method:    usleep
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_alt_collections_util_JniThreadUtil_usleep
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
